server:
  port: 8081
spring:
  application:
    name: provider-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8082
dubbo:
  scan:
    base-packages: com.lqz.demo.service
  protocol:
    name: dubbo
    port: -1
    serialization: protostuff
    charset: UTF-8