server:
  port: 8081
spring:
  application:
    name: provider-server
  main:
    # bean 默认名称相同覆盖
    allow-bean-definition-overriding: true
  cloud:
    # nacos 注册中心配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8847,127.0.0.1:8848,127.0.0.1:8849
    # sentinel 服务治理
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8082
#dubbo 配置
dubbo:
  #提供服务类路径
  scan:
    base-packages: com.lqz.demo.service
  #dubbo 基础配置
  protocol:
    name: dubbo
    port: -1
    serialization: protostuff
    charset: UTF-8
  cloud:
    subscribed-services: